export default {
  BACKEND_URL_PROJECT_INFO: process.env.VUE_APP_PROJECT_INFO,
  BACKEND_URL_PROJECT_PROGRESS: process.env.VUE_APP_PROJECT_PROGRESS,
  BACKEND_URL_DIC: `/api`,
  BACKEND_URL_PROJECT_MESSAGE: process.env.VUE_APP_PROJECT_MESSAGE,
  BACKEND_URL_PROJECT_MICROAPP: process.env.VUE_APP_PROJECT_MICROAPP
}
